"""Interactive HTML report generator for user profiles."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..analysis.profiler import UserProfile

logger = logging.getLogger(__name__)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} - 知乎人物画像</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"></script>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
    background: #f5f7fa;
    color: #2c3e50;
    line-height: 1.6;
}}
.container {{ max-width: 960px; margin: 0 auto; padding: 24px; }}
.header {{
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 48px 32px;
    border-radius: 16px;
    margin-bottom: 24px;
    text-align: center;
}}
.header h1 {{ font-size: 2em; margin-bottom: 8px; }}
.header p {{ opacity: 0.85; font-size: 1.05em; }}
.card {{
    background: white;
    border-radius: 12px;
    padding: 28px;
    margin-bottom: 20px;
    box-shadow: 0 2px 12px rgba(0,0,0,0.06);
}}
.card h2 {{
    font-size: 1.25em;
    margin-bottom: 16px;
    padding-bottom: 12px;
    border-bottom: 2px solid #f0f0f0;
    color: #764ba2;
}}
.stats-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 16px;
    margin-bottom: 16px;
}}
.stat-box {{
    text-align: center;
    padding: 20px 12px;
    background: #f8f9fc;
    border-radius: 10px;
    border: 1px solid #eef0f5;
}}
.stat-value {{ font-size: 1.8em; font-weight: 700; color: #667eea; }}
.stat-label {{ font-size: 0.85em; color: #888; margin-top: 4px; }}
.chart {{ width: 100%; height: 380px; }}
.chart-sm {{ width: 100%; height: 280px; }}
.tag {{
    display: inline-block;
    padding: 6px 14px;
    margin: 4px;
    border-radius: 20px;
    font-size: 0.88em;
    background: #f0e6ff;
    color: #764ba2;
    border: 1px solid #e0d0f0;
}}
.tag-primary {{
    background: linear-gradient(135deg, #667eea, #764ba2);
    color: white;
    border: none;
    font-weight: 500;
}}
.trait-bar {{
    display: flex;
    align-items: center;
    margin: 12px 0;
}}
.trait-label {{
    width: 100px;
    font-size: 0.9em;
    color: #555;
    text-align: right;
    padding-right: 12px;
}}
.trait-track {{
    flex: 1;
    height: 22px;
    background: #f0f0f0;
    border-radius: 11px;
    overflow: hidden;
}}
.trait-fill {{
    height: 100%;
    border-radius: 11px;
    transition: width 0.6s ease;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    padding-right: 10px;
    font-size: 0.8em;
    color: white;
    font-weight: 500;
    min-width: 36px;
}}
.section-desc {{
    color: #666;
    font-size: 0.95em;
    margin-bottom: 16px;
    line-height: 1.7;
}}
.summary-box {{
    background: #faf8ff;
    border-left: 4px solid #764ba2;
    padding: 16px 20px;
    border-radius: 0 10px 10px 0;
    margin: 16px 0;
    white-space: pre-line;
    font-size: 0.95em;
    line-height: 1.7;
    color: #444;
}}
.footer {{
    text-align: center;
    color: #aaa;
    font-size: 0.85em;
    padding: 32px 0 16px;
}}
@media (max-width: 640px) {{
    .container {{ padding: 12px; }}
    .header {{ padding: 32px 20px; }}
    .header h1 {{ font-size: 1.5em; }}
    .card {{ padding: 20px; }}
    .stats-grid {{ grid-template-columns: repeat(2, 1fr); }}
}}
</style>
</head>
<body>
<div class="container">

<div class="header">
    <h1>{name}</h1>
    <p>{headline}</p>
</div>

{stats_html}

{personality_html}

{interests_html}

{values_html}

{sentiment_html}

{style_html}

{timeline_html}

{evolution_html}

<div class="footer">
    <p>Generated by Zhihu Profiler · {generated_at}</p>
</div>

</div>
<script>
{charts_js}
</script>
</body>
</html>"""


class ReportGenerator:
    """Generates self-contained HTML reports with interactive visualizations."""

    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = output_dir or Path("output")

    def generate(self, profile: UserProfile, output_path: Optional[Path] = None) -> Path:
        """Generate the full HTML report."""
        if output_path is None:
            user_id = profile.user.get("id", "unknown") if profile.user else "unknown"
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.output_dir / f"{user_id}_{timestamp}.html"

        output_path.parent.mkdir(parents=True, exist_ok=True)

        html = self._build_html(profile)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        logger.info(f"Report generated: {output_path}")
        return output_path

    def _build_html(self, profile: UserProfile) -> str:
        """Build the complete HTML string."""
        user = profile.user or {}

        return HTML_TEMPLATE.format(
            title=user.get("name", "Unknown"),
            name=user.get("name", "Unknown User"),
            headline=user.get("headline", "知乎用户"),
            generated_at=profile.analyzed_at[:19] if profile.analyzed_at else "",
            stats_html=self._build_stats_html(profile),
            personality_html=self._build_personality_html(profile),
            interests_html=self._build_interests_html(profile),
            values_html=self._build_values_html(profile),
            sentiment_html=self._build_sentiment_html(profile),
            style_html=self._build_style_html(profile),
            timeline_html=self._build_timeline_html(profile),
            evolution_html=self._build_evolution_html(profile),
            charts_js=self._build_charts_js(profile),
        )

    def _build_stats_html(self, profile: UserProfile) -> str:
        """Build stats overview section."""
        user = profile.user or {}
        return f"""
<div class="card">
    <h2>基础数据</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-value">{profile.total_answers}</div>
            <div class="stat-label">回答数</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{self._format_number(profile.total_chars)}</div>
            <div class="stat-label">总字数</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{self._format_number(profile.total_upvotes)}</div>
            <div class="stat-label">总赞同</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{self._format_number(user.get('follower_count', 0))}</div>
            <div class="stat-label">关注者</div>
        </div>
    </div>
    <div style="text-align:center;color:#888;font-size:0.9em;">
        {f"时间跨度：{profile.date_range[0]} ~ {profile.date_range[1]}" if profile.date_range else ""}
    </div>
</div>"""

    def _build_personality_html(self, profile: UserProfile) -> str:
        if not profile.personality:
            return ""
        p = profile.personality
        bf = p.get("big_five", {})

        trait_names = {
            "openness": "开放性",
            "conscientiousness": "尽责性",
            "extraversion": "外向性",
            "agreeableness": "宜人性",
            "neuroticism": "神经质",
        }
        trait_colors = {
            "openness": "#667eea",
            "conscientiousness": "#764ba2",
            "extraversion": "#f093fb",
            "agreeableness": "#4facfe",
            "neuroticism": "#43e97b",
        }

        bars = ""
        for key, name in trait_names.items():
            score = bf.get(key, 50)
            color = trait_colors.get(key, "#667eea")
            bars += f"""
        <div class="trait-bar">
            <div class="trait-label">{name}</div>
            <div class="trait-track">
                <div class="trait-fill" style="width:{score}%;background:{color}">{score:.0f}</div>
            </div>
        </div>"""

        return f"""
<div class="card">
    <h2>人格特征 · 大五人格</h2>
    {bars}
    <div class="summary-box">{p.get('summary', '')}</div>
    <div class="section-desc">
        认知方式：{p.get('cognitive_style', '')}<br>
        社交倾向：{p.get('social_orientation', '')}<br>
        风险偏好：{p.get('risk_tolerance', '')}
    </div>
</div>"""

    def _build_interests_html(self, profile: UserProfile) -> str:
        if not profile.interests:
            return ""
        interests = profile.interests
        top = interests.get("top_domains", [])[:8]

        tags = ""
        for i, (domain, score) in enumerate(top):
            cls = "tag-primary" if i == 0 else ""
            tags += f'<span class="tag {cls}">{domain}</span>'

        return f"""
<div class="card">
    <h2>兴趣领域</h2>
    <div style="margin-bottom:12px">{tags}</div>
    <div id="interests-chart" class="chart-sm"></div>
    <div class="section-desc">{interests.get('summary', '')}</div>
</div>"""

    def _build_values_html(self, profile: UserProfile) -> str:
        if not profile.values:
            return ""
        v = profile.values
        cores = v.get("core_values", [])

        tags = ""
        for c in cores:
            tags += f'<span class="tag tag-primary">{c}</span>'

        return f"""
<div class="card">
    <h2>价值体系</h2>
    <div style="margin-bottom:12px">{tags}</div>
    <div id="values-chart" class="chart-sm"></div>
    <div class="summary-box">{v.get('summary', '')}</div>
</div>"""

    def _build_sentiment_html(self, profile: UserProfile) -> str:
        if not profile.sentiment:
            return ""
        s = profile.sentiment
        return f"""
<div class="card">
    <h2>情感基调</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-value">{s.get('overall_score', 0.5):.2f}</div>
            <div class="stat-label">情感得分</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{s.get('positive_ratio', 0):.0%}</div>
            <div class="stat-label">积极比例</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{s.get('emotional_stability', 0):.2f}</div>
            <div class="stat-label">情绪稳定度</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{s.get('trend', 'stable')}</div>
            <div class="stat-label">情感趋势</div>
        </div>
    </div>
    <div class="summary-box">{s.get('description', '')}</div>
</div>"""

    def _build_style_html(self, profile: UserProfile) -> str:
        if not profile.style:
            return ""
        style = profile.style

        devices = style.get("rhetorical_devices", {})
        device_tags = ""
        for device, count in list(devices.items())[:6]:
            device_tags += f'<span class="tag">{device}({count})</span>'

        return f"""
<div class="card">
    <h2>表达风格</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-value">{style.get('avg_sentence_length', 0):.0f}</div>
            <div class="stat-label">平均句长</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{style.get('avg_answer_length', 0):.0f}</div>
            <div class="stat-label">平均回答长度</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{style.get('vocabulary_richness', 0):.2f}</div>
            <div class="stat-label">词汇丰富度</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{style.get('first_person_ratio', 0):.3f}</div>
            <div class="stat-label">第一人称比</div>
        </div>
    </div>
    <div class="section-desc">
        语气风格：{style.get('tone_style', '')}<br>
        结构风格：{style.get('structural_style', '')}<br>
        标点风格：{style.get('punctuation_style', '')}
    </div>
    {f'<div style="margin-top:8px">{device_tags}</div>' if device_tags else ''}
    <div class="summary-box">{style.get('summary', '')}</div>
</div>"""

    def _build_timeline_html(self, profile: UserProfile) -> str:
        if not profile.timeline:
            return ""
        t = profile.timeline
        events_html = ""
        for e in t.get("events", [])[:10]:
            events_html += f"""
        <div style="padding:10px 16px;margin:6px 0;background:#f8f9fc;border-radius:8px;font-size:0.9em;">
            <div style="display:flex;gap:8px;align-items:center;margin-bottom:4px;">
                <span style="background:var(--primary-light,#a29bfe);color:white;padding:2px 10px;border-radius:10px;font-size:0.78em;white-space:nowrap;">{e.get('category', '')}</span>
                <span style="color:#888;font-size:0.82em;">{e.get('date', '')}</span>
            </div>
            <div style="color:#444;line-height:1.5;">{e.get('description', '')[:150]}</div>
        </div>"""

        phases_html = ""
        for p in t.get("phases", []):
            themes = " · ".join(p.get("themes", [])[:3])
            phases_html += f"""<div style="padding:6px 12px;margin:4px 0;font-size:0.85em;">
            <strong>{p.get('year', '')}</strong> — {p.get('answer_count',0)}条回答 · {themes}
            </div>"""

        return f"""
<div class="card">
    <h2>个人时间线</h2>
    <h3 style="font-size:0.95em;color:var(--text-secondary);margin-bottom:10px;">关键事件</h3>
    {events_html if events_html else '<p style="color:#999;">暂未检测到明确的人生事件</p>'}
    <h3 style="font-size:0.95em;color:var(--text-secondary);margin:16px 0 10px;">活跃阶段</h3>
    {phases_html}
    <div class="summary-box">{t.get('summary', '')}</div>
</div>"""

    def _build_evolution_html(self, profile: UserProfile) -> str:
        if not profile.evolution:
            return ""
        ev = profile.evolution
        points_html = ""
        for p in ev.get("points", []):
            topics = " · ".join(p.get("topics", [])[:4])
            phrases = " ".join([f"<span style='color:var(--primary);font-size:0.82em;'>{ph}</span>" for ph in p.get("transition_phrases", [])[:3]])
            points_html += f"""
        <div style="padding:8px 14px;margin:4px 0;border-left:3px solid var(--primary-light,#a29bfe);font-size:0.88em;">
            <strong>{p.get('period', '')}</strong>
            <span style="color:#888;margin-left:8px;">{p.get('answer_count',0)}条 · 均长{p.get('avg_length',0)}字 · 情感{p.get('sentiment',0.5):.2f}</span>
            {f'<div style="margin-top:4px;color:#555;">{topics}</div>' if topics else ''}
            {f'<div style="margin-top:4px;">{phrases}</div>' if phrases else ''}
        </div>"""

        return f"""
<div class="card">
    <h2>思想演变</h2>
    <div id="evolution-chart" class="chart-sm"></div>
    {points_html}
    <div class="summary-box">{ev.get('summary', '')}</div>
</div>"""

    def _build_charts_js(self, profile: UserProfile) -> str:
        """Build all ECharts JavaScript."""
        js = ""

        # Interests donut chart
        if profile.interests:
            interests = profile.interests.get("top_domains", [])[:8]
            data = [{"name": name, "value": round(score, 1)} for name, score in interests]
            if data:
                js += f"""
(function() {{
    var chart = echarts.init(document.getElementById('interests-chart'));
    chart.setOption({{
        tooltip: {{ trigger: 'item' }},
        series: [{{
            type: 'pie',
            radius: ['40%', '70%'],
            itemStyle: {{ borderRadius: 6, borderColor: '#fff', borderWidth: 2 }},
            label: {{ show: true, formatter: '{{b}}\\n{{d}}%' }},
            data: {json.dumps(data, ensure_ascii=False)}
        }}]
    }});
}})();
"""

        # Values radar chart
        if profile.values:
            values = profile.values.get("value_scores", {})
            if values:
                dims = list(values.keys())
                scores = [values[d] for d in dims]
                js += f"""
(function() {{
    var chart = echarts.init(document.getElementById('values-chart'));
    chart.setOption({{
        tooltip: {{}},
        radar: {{
            indicator: {json.dumps([{"name": d, "max": 100} for d in dims], ensure_ascii=False)},
            center: ['50%', '55%'],
            radius: '65%',
        }},
        series: [{{
            type: 'radar',
            data: [{{ value: {json.dumps(scores)}, name: '价值倾向' }}],
            areaStyle: {{ color: 'rgba(102, 126, 234, 0.2)' }},
            lineStyle: {{ color: '#667eea' }},
            itemStyle: {{ color: '#764ba2' }},
        }}]
    }});
}})();
"""

        # Evolution line chart
        if profile.evolution:
            ev = profile.evolution
            periods = [p.get("period", "") for p in ev.get("points", [])]
            sentiments = [p.get("sentiment", 0.5) for p in ev.get("points", [])]
            lengths = [p.get("avg_length", 0) for p in ev.get("points", [])]
            if periods and len(periods) >= 2:
                js += f"""
(function() {{
    var chart = echarts.init(document.getElementById('evolution-chart'));
    chart.setOption({{
        tooltip: {{ trigger: 'axis' }},
        legend: {{ data: ['情感得分', '平均篇幅'], bottom: 0 }},
        xAxis: {{ type: 'category', data: {json.dumps(periods, ensure_ascii=False)} }},
        yAxis: [
            {{ type: 'value', name: '情感', min: 0, max: 1 }},
            {{ type: 'value', name: '字数' }}
        ],
        series: [
            {{
                name: '情感得分',
                type: 'line',
                data: {json.dumps(sentiments)},
                smooth: true,
                lineStyle: {{ color: '#764ba2' }},
                itemStyle: {{ color: '#764ba2' }}
            }},
            {{
                name: '平均篇幅',
                type: 'line',
                yAxisIndex: 1,
                data: {json.dumps(lengths)},
                smooth: true,
                lineStyle: {{ color: '#00b894', type: 'dashed' }},
                itemStyle: {{ color: '#00b894' }}
            }}
        ]
    }});
}})();
"""

        return js

    @staticmethod
    def _format_number(n: int) -> str:
        """Format number with k/m suffix."""
        if n >= 1_000_000:
            return f"{n / 1_000_000:.1f}M"
        elif n >= 1_000:
            return f"{n / 1_000:.1f}K"
        return str(n)
